---
title: "ShinyApp"
author: "Oliver Cornelius-Knudsen"
date: "12/13/2017"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
percent_map <- function(var, color, legend.title, min = 0, max = 100) {

  # generate vector of fill colors for map
  shades <- colorRampPalette(c("white", color))(100)
  
  # constrain gradient to percents that occur between min and max
  var <- pmax(var, min)
  var <- pmin(var, max)
  percents <- as.integer(cut(var, 100, 
    include.lowest = TRUE, ordered = TRUE))
  fills <- shades[percents]

  # plot choropleth map
  map("county", fill = TRUE, col = fills, 
    resolution = 0, lty = 0, projection = "polyconic", 
    myborder = 0, mar = c(0,0,0,0))
  
  # overlay state borders
  map("state", col = "white", fill = FALSE, add = TRUE,
    lty = 1, lwd = 1, projection = "polyconic", 
    myborder = 0, mar = c(0,0,0,0))
  
  # add a legend
  inc <- (max - min) / 4
  legend.text <- c(paste0(min, " % or less"),
    paste0(min + inc, " %"),
    paste0(min + 2 * inc, " %"),
    paste0(min + 3 * inc, " %"),
    paste0(max, " % or more"))
  
  legend("bottomleft", 
    legend = legend.text, 
    fill = shades[c(1, 25, 50, 75, 100)], 
    title = legend.title)
}
```

```{r}
library(shiny)
library(maps)
library(mapproj)

ui <- fluidPage ( 
  titlePanel("County Level Mortality"),
  
  sidebarLayout(
    helpText("See how accurately our predictive models are able to predict 
             the mortality rate for a given cause of death."),
    selectInput("var",
                label = "Choose Cause of Death",
                choices = list("HIV", "Maternal Disorders", "Common Infectious Diseases",
                               "Neglected Tropical Diseases", "Neonatal Disorders", "OTHC", 
                               "Neoplasms"),
                selected = "HIV"),
  ),
  
    mainPanel(plotOutput(percent_map(input$var, "darkred", "USA")))
  
  
)
  

  
  
server <- function(input, output) {
  
  output$map <- renderPlot({
    
    data <- switch(input$var, 
                   "HIV" <- results$`HIV14$HIVtreediff`,
                   "Maternal Disorders" <- results$`MAT14$MATtreediff`)
    
    
    percent_map(input$var, "darkred", "USA")
    
  })
}
  
  
shinyApp(ui = ui, server = server)  

```